version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    links:
      - db
    environment:
      DB_ROOT_PASSWORD: postgres
      DB_ROOT_USER: postgres
    ports:
      - "8080:8080"
